name: CORTEX
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - azure-core==1.36.0
      - azure-cosmos==4.14.1
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - fastapi==0.115.4
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - httplib2==0.31.0
      - idna==3.11
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - python-dotenv==1.0.1
      - python-multipart==0.0.12
      - requests==2.32.5
      - rsa==4.9.1
      - sniffio==1.3.1
      - starlette==0.41.3
      - tinydb==4.8.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.32.0
prefix: /home/dstonebreaker/anaconda3/envs/CORTEX
